name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13e2136ff60e9c06778af8d93c558da380aaea41d66d6a0aa1a1f56d3afba241"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
