name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed65074e130a75404d3fcaf73ac3609bd4c7c2a3af929b0e287a41b4dafe2e93"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
