name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c83db1625a00e3a74fd104a10c6745583771b6e84c42f3d802b466f7c757742f"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
