name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f958e6abd25b0f870c19784d8fef376476dc0a0a7c3eb13c9b92d455d374cb3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
