name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ee1c56f077eb56fc152f48698c3fee2bf79fa0c7163592fa9fa6e3cf7bcb24"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
