name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5079ab23b89ae0756d978d0fc229c0b139ac1f82312fc0f46edf869ff7ca7536"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
