name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0911f92ce03b6c219f591bb79dc8cd5fbeee79fd8e85178e8c17c6d222b868b1"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
