name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2d31b451981d21bbe730fe1773f6f9c62e3c03dae77315450787e3aaf0fe3f1"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
