name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e1026bdc8ca91a259c3f90a9409f82c104e9c716080c807084fff0ff7ee80de"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
