name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e805a709e58c8e9fb049f1199e949e267ccf0b0146549b1c7393ec57f8a2a97"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
