name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49c8161fd4c824c41f73a1bb347c049644020213b22d4b801f1ace4b04d3a02d"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
