name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60829d3401d0940c15e451716d123b92f2659fe68c5237b5a1a58daac207891d"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
