name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8657e9194d9c3252d200d170d9c8aa5fcb0520612b204c55f202d1875391f3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
