name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f7a630addbc3c7ec688c094a6d663aa1a3eeb4d9ea998ce940b23ca06fa82ff"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
