name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6dc32a5248ed38b2cb5e37a7ee624c4a0f76654228817a59a25bae9a7851cb3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
