name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b1cfe4dc7cfb464d08a69273ff2bfff425f32764a14e5a286b1ba5bd930ed5b"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
