name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186e3c5dca3ee2da900d4f5241d90a9dba0e7aae808744c7b1b83502b8cbcdaa"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
