name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58e2960914b45851ddf810818903f3a620c5aa117b5c267a97e6640f8fd72456"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
