name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c357f54a443574a5287956279d067edda82f96e79d3750c62219534bb14d79a8"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
