name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a58829318af074f7a4054c3491fdd7151adea36dc924f5c6ab7d519c8a227c6b"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
