name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe9adda5d39dfce1f682051d0959bb6c3e2db1e7562cf05c90be2355cbebd3d2"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
