name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2955908ced0ccb8d14fedca1d506ea9ce9aa7ae3b41f7b2f3bd2bc83f16e20cc"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
