name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "558ba97237d01527b6032b6d1d0e41f35496f997714072ab1f37d5512376b318"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
