name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39530b3153696d2c15aebef7c8b8aeb22cc7dd72b3787dadbea544ec0992c634"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
