name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec816e72c076407e13e8b9fcd0d997d76b45f7ee0305f0d0fcb14f1efc7720f3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
