name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174e23828c84d29b490d816e7f9385a2691ea3ea9f7138f7512f04722e153509"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
