name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ad32c66294329deace0ef2c4148f9f7e162af68e19d976708c230853151903a"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
