name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "476fd0938f31022e0264f4ce095702f0c1b7ae88691d6278b29cfa2e1709b014"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
