name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "217f65142e1ce1982fb743613e30afa19573f2fc3eb1e6155500b60afa202e00"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
