name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bc15ede18b92540170ba789bc2bbca0a77ada68b3e770185c5c2643e76558fe"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
