name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25219b9b35e6966cd15a1b245d35ef2c0235202cf92d4cf390a6e56a6a73f673"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
