name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbd7e60c40e888d7e0665e0fa598494b65aac9ec5cb6309be04611b21540cc14"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
