name = "HexMC"
author = "HexMC Contributors"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d859be9a7032e11beecd8a997f2e99f34fe4211dec278b8f94673fa1122031fb"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
