name = "HexMC"
author = "HexMC Contributors"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7bccd738c155a253eb950a648c85a50ea274d63361233b52ea29f612c7ff42c"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
