name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11024ba84b380313e62530eb685e4aad865d7aa98e4b79f9f0385522d58252b2"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
