name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d4fc79aa5cfd72288a0e55868dc26b25e27e8a36c8dbf894b0e409fbc5d260"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
