name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70ae57e810843e66a06792a85bac79ff840be0e7f71d3cfd52c6b6d8837bf8fd"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
