name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eab6775efac2c3c34e97aa793c7c97ad582a4b3d792e11b25ea543e064bafcf9"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
