name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9776dc171b29889f3631dfca03aa6bd6be22bd715ebef6f6435e03c1971b135b"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
