name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e31d34e7c114efe1f8c8c174dd1ecbdb4433839e186960d58f4fac5809d1d68"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
