name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a55597810a00be8dafec9e5b23196731d54cd50486155ed7397fe21757b4b74"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
