name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0afb983a5f624a085dbd9aff1281932b16ee35cf9ea7b6d9aa1d5cde78b8360"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
