name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3cc5b440bbe3e317ea4d72ab43ca7c06a8be154cb739fc235ec7185f4b2ac90"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
