name = "HexMC"
author = "HexMC Contributors"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8d3222433742626a22d6dbeedf6582b818a104f7f3b795e42d3f72863c637d2"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
