name: Build Modpack
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip make

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Setup packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          export PATH=${PATH}:`go env GOPATH`/bin

      - name: Make Modrinth
        run: |
          make modrinth
          mkdir .modrinth && cd .modrinth
          unzip ../modpack-modrinth.zip

      - name: Make PolyMC (Auto Update)
        run: |
          make polymc

      - name: Make Technic
        run: |
          make technic

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC-Modrinth
          path: .modrinth
          
      - name: Upload PolyMC (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: HexMC-PolyMC-Auto
          path: modpack-polymc.zip

      - name: Upload Technic
        uses: actions/upload-artifact@v3
        with:
          name: HexMC-Technic
          path: .technic
